
export const HOTSPOT_CLICKED = "HOTSPOT_CLICKED";
export const HOTSPOT_MOUSE_OVER = "HOTSPOT_MOUSE_OVER";
export const HOTSPOT_MOUSE_OUT = "HOTSPOT_MOUSE_OUT";

export const CAMERA_ROTATION = "CAMERA_ROTATION";
export const SCENE_SCREEN_SHOT = "SCENE_SCREEN_SHOT";
export const RESIZE = "RESIZE";
